### ISSUE TITLE
Hi Shi-Qi-Li,

### ISSUE THREAD

**Issue by YangYangLeo** [Shi-Qi-Li/Shi-Qi-Li.github.io#1]
Hi, I am really thankful you share me your idea about submission in NUPLAN. However, there is still an issue comming out. Would you mind give me your wechat number to me that I can ask your just a few question simply. If so, I  will be really thankful because I am in submission trouble long time. It suffers me a lot.

**Comment by Shi-Qi-Li** [comment]
> Hi, I am really thankful you share me your idea about submission in NUPLAN. However, there is still an issue comming out. Would you mind give me your wechat number to me that I can ask your just a few question simply. If so, I will be really thankful because I am in submission trouble long time. It suffers me a lot.

You can leave me a email address that I can sent you my wechat QR code.
